datastoreName = "walkforward_models"
dataSourcesDatastoreName = "gridworld_datasources"
predictionsName = "walkforward_predictions"
portfolioDB = "walkforward_portfolios"
portfolioLookup = "walkforward_portfolio_info"
portfolioAllocation = "walkforward_portfolio_allocation"
aggregatePrediction = "walkforward_aggregate_predictions"
portfolioDataCache = "walkforward_portfolio_data"
portfolioQuickCache = "walkforward_quick_cache"
trainingDataCache = "walkforward_training_cache"
modelDataCache = "walkforward_model_cache"
tradingPortfolios = "walkforward_trading_portfolios"

##TRADING
portfolioDataTradingCache = "walkforward_portfolio_trading_data"
portfolioQuickTradingCache = "walkforward_quick_tradong_cache"